version: '3.8'

services:
  # API OCR
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ocr-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DOCTR_CACHE_DIR=/app/.doctr_cache
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - doctr_cache:/app/.doctr_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ocr/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - ocr-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ocr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ocr-network

volumes:
  redis_data:
  doctr_cache:

networks:
  ocr-network:
    driver: bridge 